### ISSUE TITLE
Metadata in profiles doesn't show in web UI, and looks a little odd in public profile pages

### ISSUE THREAD

**Issue by Cassolotl** [unascribed/sleeping.town#18]
I've got some metadata in my profile like so:

![screen shot 2018-04-23 at 23 18 59](https://user-images.githubusercontent.com/6607512/39156137-d0977252-474c-11e8-94e6-7508641b9969.png)

It doesn't show up on my profile in the web UI at all:

![screen shot 2018-04-23 at 23 19 53](https://user-images.githubusercontent.com/6607512/39156155-e369e20c-474c-11e8-957c-84820116c0c6.png)

And it looks a little odd in the [profile page](https://sleeping.town/@cassolotl):

![screen shot 2018-04-23 at 23 20 34](https://user-images.githubusercontent.com/6607512/39156188-f790de3e-474c-11e8-8b54-5f3282b2e639.png)

I'm using the _Dawn (Light)_ flavour.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by unascribed** [comment]
babfae7734c1ee20109bb1a282415d890ba250be

**Comment by Cassolotl** [comment]
Ohhh what does this mean?

**Comment by unascribed** [comment]
The commit I linked fixes this issue, and will be deployed soon.

**Comment by Cassolotl** [comment]
Ahhh thank you! :) <3
