### ISSUE TITLE
i can't post anything

### ISSUE THREAD

**Issue by sleepythymes** [unascribed/sleeping.town#21]
<img width="277" alt="screen shot 2018-04-24 at 2 42 48 pm" src="https://user-images.githubusercontent.com/38702513/39207378-c8481bde-47cd-11e8-91c2-a7e6b8cc5d89.png">
it might just be me being dumb but this is what the sitch is. also nothing pops up if i try to reply or anything

**Comment by sleepythymes** [comment]
no i switched over to glitchsoc and i've been able to post no problem.

**Comment by strdr1ft** [comment]
this seems to be an issue in chrome, as we're having it too, as well as the boost button being offset
![image](https://user-images.githubusercontent.com/36276280/39254476-298f0b46-4878-11e8-9426-db6afc48d6be.png)

works fine in firefox, though

**Comment by unascribed** [comment]
banish chrome

**Comment by strdr1ft** [comment]
i have switched yet, i need to ;w;

**Comment by unascribed** [comment]
I was about to say I can't reproduce this, but I accidentally fixed it while working on #20
