### ISSUE TITLE
Favicon thing is broken on sleeping.town and cassolotl.sleeping.town

### ISSUE THREAD

**Issue by Cassolotl** [unascribed/sleeping.town#25]
It looks like this:

![screen_shot_2018-04-27_at_12_37_39](https://user-images.githubusercontent.com/6607512/39360892-f1259760-4a17-11e8-9079-65dc9bf2350f.png)

I'm on Chrome (65.0.3325.181 (Official Build) (64-bit)) on a Mac (10.13.4), if that helps! :) And I use ublock origin.

**Comment by unascribed** [comment]
As far as I can tell, this is an intermittent issue related to the media server taking a few minutes to start serving newly uploaded media, and is not an issue with the favicon setting.
