### ISSUE TITLE
Expanded Notifications just look really bad

### ISSUE THREAD

**Issue by oct2pus** [unascribed/sleeping.town#26]
![image](https://user-images.githubusercontent.com/30452393/39399308-29e4789a-4ae1-11e8-9af9-30c3f805c49e.png)
I have no idea what to title this it just looks really bad

**Comment by unascribed** [comment]
wow

**Comment by unascribed** [comment]
I've decided to deprecate the Sleeping flavor, as it's become a maintenance burden I don't have time for.

**Comment by unascribed** [comment]
Oops I changed my mind
