### ISSUE TITLE
"Learn more" links to joinmastodon.org

### ISSUE THREAD

**Issue by Yukitty** [unascribed/sleeping.town#28]
The "Find another instance" button links to "Dzuk's Cool Instances list, not the usual Mastodon Instances list."

But if you scroll all the way down and click the "Learn more" button at the bottom, it sends you to `joinmastodon.org` instead.

That's intentional, right? Just making sure.

**Comment by unascribed** [comment]
Not intentional, though I don't think it's an issue, since that "Learn more" button is to learn more about the Mastodon project, which joinmastodon.org does well. Dzuk's instance list is just an instance list.

**Comment by Yukitty** [comment]
Are there any links to https://sleeping.town/about/more at all?? Because that's what I was actually trying to find.

**Comment by unascribed** [comment]
I think so? It's not really clear where they are though. I'm not a fan of this design for the homepage for that reason.

**Comment by unascribed** [comment]
Yeah, "Learn more" to the right of the admin name is a link to /about/more.

**Comment by Yukitty** [comment]
What! But that looks like it's gonna link to your admin profile! >.< How silly!
