### ISSUE TITLE
[Noon] Color of "Back" in 4th pane when you view a toot is a very unreadable blue instead of white

### ISSUE THREAD

**Issue by oct2pus** [unascribed/sleeping.town#29]
![image](https://user-images.githubusercontent.com/30452393/40306448-6069c006-5cc4-11e8-987f-b1982ac86d49.png)
Currently just using standard Firefox on Linux.

**Comment by unascribed** [comment]
This is a side-effect of the Glitchsoc update I did in a panic the other day for the security issue, among a ton of other contrast and color issues.

**Comment by unascribed** [comment]
I've decided to deprecate the Sleeping flavor, as it's become a maintenance burden I don't have time for.

**Comment by unascribed** [comment]
Oops I changed my mind
