### ISSUE TITLE
Sleeping town goes blank shortly after page loads

### ISSUE THREAD

**Issue by oct2pus** [unascribed/sleeping.town#30]
I really don't know what to say here. it displays shortly while page content is still loading, and then goes white.

Before:
![image](https://user-images.githubusercontent.com/30452393/40586134-c39329f2-6182-11e8-9f57-253acb79b9fb.png)

After
![image](https://user-images.githubusercontent.com/30452393/40586136-cef8e8fe-6182-11e8-82ca-890f2b6bf1fd.png)

**Comment by oct2pus** [comment]
https://sleeping.town/settings/preferences

I can access the preference page through a direct link

**Comment by oct2pus** [comment]
I've confirmed that glitch sock and default mastodon flavors do not break

**Comment by oct2pus** [comment]
Sleeping is currently working, im suspecting someone blogged something that broke it similar to a previous issue where a pleroma profile with a custom emoji broke the Web UI.

**Comment by oct2pus** [comment]
![image](https://user-images.githubusercontent.com/30452393/40885847-e0729618-66f3-11e8-91f6-e13a5de87e48.png)
one of these 4 posts breaks the sleeping town flavor

**Comment by falkreon** [comment]
Often I find that if I leave sleeping open for a long time, an update will break the connection from my locally-cached page. Try shift+reloading, that almost always fixes the problem for me.

**Comment by unascribed** [comment]
Please send the contents of your browser console (press F12)

**Comment by oct2pus** [comment]
https://paste.debian.net/1027778/

**Comment by oct2pus** [comment]
[Closing this issue because of the remove of the sleeping theme](https://sleeping.town/@announce/100220875969448155)

**Comment by unascribed** [comment]
Oops I changed my mind
