### ISSUE TITLE
Can't upload .gif avatar even if image is less than 2MB

### ISSUE THREAD

**Issue by Crakila** [unascribed/sleeping.town#41]
When attempting to upload a new avatar, it returns the error that the file has to be less than 2MB.
The image that I am trying to upload is a .gif at 1.4MB as per the screenshot here:

![screenshot_2018-08-09_13-42-46](https://user-images.githubusercontent.com/42216004/43899664-87140144-9bda-11e8-8316-13414f336115.png)

Any help would be appreciated.

:smile:

**Comment by unascribed** [comment]
Mastodon attempts to "optimize" the compression of GIF avatars and headers, and this often results in the file becoming larger.
