### ISSUE TITLE
favs on dms are not very visible

### ISSUE THREAD

**Issue by hoodieak** [unascribed/sleeping.town#42]
![image](https://user-images.githubusercontent.com/23704040/44004249-9f8e4504-9e2d-11e8-8fdc-834f7999c264.png)
default sleeping.town theme has a bit of a color issue with finding favs hard to see on direct messages. its not majorly bad, and it might even be in that grey area of colors where its not killer to the app for most users, but it is hard on my tired eyes

switching to midnight resolved it and i love midnight too coz dark themes are my fav! will possibly PR it if  i can find a decent solution

**Comment by unascribed** [comment]
oh geez. I haven't really looked at DMs on Dusk, this is Pretty Awful

I spend all my time on Noon so DMs there are basically perfect but I haven't really touched them in the other skins

**Comment by unascribed** [comment]
The algorithm used to decide colors in Sleeping v2 is not susceptible to this problem.
