### ISSUE TITLE
bofa.lol still federates despite being blocked

### ISSUE THREAD

**Issue by oct2pus** [unascribed/sleeping.town#49]
I've discussed this with una privately but for posterities sake I think it should probably be listed as an issue here.

**Comment by falkreon** [comment]
More accurately, it has stopped federating. If you go to any person's offsite profile, you'll notice that there have been way more posts since we stopped talking.

**Comment by oct2pus** [comment]
So are some messages just arriving late, and after that no more bofa?

it's supposed to not be federating according to Una, as she blocked the instance.

**Comment by unascribed** [comment]
I don't know what's going on here, but it is bizarre and it's not just a matter of old posts still showing up; I saw a post made only 5 hours ago on a user's profile earlier today.

**Comment by falkreon** [comment]
Now that I'm back at a desktop: Triple-checked that we have a full suspension on bofa, and the media removal is working, but just today I saw more evidence of continued post federation even though the images are gone.

**Comment by oct2pus** [comment]
closing these since otherwise github wont stop annoying me w/ them and im banned anyways lmaoz
